spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/optocon?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0

#jackson配置
spring.jackson.serialization.indent_output: true
spring.http.converters.preferred-json-mapper: jackson
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.joda-date-time-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: GMT+8
logging:
  level:
    root: debug
